"""Produce a cold-setup-inclusive report from a complete validated matrix."""
import csv
import io
import math
import re
from pathlib import Path
import statistics
import subprocess
import sys

folder = Path(sys.argv[1])
summarizer = Path(__file__).with_name('summarize-strip24-suite.py')
result = subprocess.run([sys.executable, str(summarizer), str(folder)],
                        capture_output=True, text=True, check=True)
rows = list(csv.DictReader(io.StringIO(result.stdout)))
assert len(rows) == 43, 'Full suite requires 43 cases'
for r in rows:
    for k in r:
        if k != 'case':
            r[k] = float(r[k])
ratios = [r['cold_setup_pfxt_ms_speedup'] for r in rows]
print('# Strip24 full-suite comparison\n')
print('RTX 5090; K=1M; maintained bound enabled; candidate arena disabled. '
      'All headline times include **cold static setup + PFXT**. '
      'Graph-file loading and SFXT are excluded. '
      'Medians of three standalone repetitions per variant, alternating order.\n')
print('The baseline is tight-bound adaptive deferral with only the existing '
      '204-byte descriptor format, not original GPG. The new mode adds '
      '24-byte single-parent strips alongside those descriptors.\n')
print('| Benchmark | Baseline ms | +Strip24 ms | Speedup | Saved ms |')
print('|---|---:|---:|---:|---:|')
for r in rows:
    b = r['cold_setup_pfxt_ms_0']; n = r['cold_setup_pfxt_ms_1']
    name = re.sub(r'_(d\d+|x\d+)$', r' \1', r['case'].replace('_base',''))
    print(f'| {name} | {b:.3f} | {n:.3f} | {b/n:.3f}x | {b-n:+.3f} |')
print('\nPositive saved milliseconds mean faster; negative means slower.\n')
print(f'Geometric-mean speedup across all 43 cases: '
      f'{math.exp(statistics.mean(math.log(x) for x in ratios)):.3f}x.\n')
print('## Regressions and hybrid-policy evidence\n')
losses = sorted((r for r in rows if r['cold_setup_pfxt_ms_speedup'] < 1),
                key=lambda r:r['cold_setup_pfxt_ms_1']-r['cold_setup_pfxt_ms_0'],
                reverse=True)
print('| Regressing case | Extra ms | Slower | New strips | Packed paths | Later promoted |')
print('|---|---:|---:|---:|---:|---:|')
for r in losses:
    b = r['cold_setup_pfxt_ms_0']; n = r['cold_setup_pfxt_ms_1']
    packed = r['represented_1']; promoted = r['promoted_1']
    fraction = f'{100*promoted/packed:.2f}%' if packed else 'N/A'
    print(f"| {r['case']} | {n-b:.3f} | {(n/b-1)*100:.2f}% | "
          f"{int(r['descriptors_1']):,} | {int(packed):,} | {fraction} |")
print('\nSmall absolute losses on already-fast cases do not by themselves '
      'justify a new dispatcher. Promotion fractions are retrospective evidence, '
      'not information assumed known by a prospective policy. '
      'The implementation also changes count aggregation, so this experiment '
      'does not isolate compression from producer changes.\n')
print('## Correctness and measurement boundaries\n')
print('All 86 pre-timing variant/case validations and 258 timed queries must '
      'pass the GPG K-cost golden comparator before this report is generated. '
      'The comparator uses 1e-3 absolute + 1e-6 relative tolerance; it is not '
      'bitwise equality. Existing corrected goldens are reused; missing ones '
      'are generated by GPG.\n')
print('Descriptor classification, allocation/growth, creation, accounting, '
      'promotion and fallback costs are inside PFXT. Static setup is added '
      'per trial before taking the median. No new memory pool is enabled. '
      'GPU occupancy checks occur before each query, not continuously. '
      'Sub-percent differences should not be interpreted as established gains.\n')
print(f'Raw matrix: `{folder}`. CSV is produced by '
      '`scripts/summarize-strip24-suite.py` using the same directory.\n')
